### ISSUE TITLE
Add option to view cart

### ISSUE THREAD

**Issue by Jake-Fisher** [Jake-Fisher/vegetableshopping-application#3]

**Comment by Jake-Fisher** [comment]
View cart option is not working at final checkout page.

**Comment by shridhar-coder** [comment]
[shopvege.zip](https://github.com/Jake-Fisher/vegetableshopping-application/files/9761737/shopvege.zip)

**Comment by shridhar-coder** [comment]
Try integrating the above file in the project. Should work without any issue.
